# Generated by Django 6.0.2 on 2026-03-21 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_family'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Family',
            new_name='family',
        ),
    ]
