# Generated by Django 6.0.2 on 2026-03-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'まだだよ'), ('in_progress', 'やってるよ'), ('done', 'できたよ')], default='todo', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('mama', 'ママ'), ('papa', 'パパ'), ('child', '子ども')], max_length=10),
        ),
    ]
