# Generated by Django 6.0.2 on 2026-03-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_status_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='code',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
